{% set name = "splore" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e71b1b8895e26dd371369e5b2e558504d2db6566e161446acab80b0e3b5098fd

build:
  noarch: python
  number: 0
  entry_points:
    - splore = splore.cli:main

requirements:
  build:
    - nodejs =14
  host:
    - python >=3.8
    - pip
  run:
    - python
    - click
    - rdkit
    - rich
    - pydantic
    - fastapi
    - uvicorn

test:
  imports:
    - splore
  commands:
    - splore --help

about:
  home: https://github.com/SimonBoothroyd/splore
  license: MIT
  license_file:
    - LICENSE
    - LICENSE-3RD-PARTY
  summary: A GUI for exploring sets of molecules
  description: |
    The splore framework aims to offer a simple graphical interface for scrolling through 
    and exploring data sets of molecules.
  doc_url: https://github.com/SimonBoothroyd/splore
  dev_url: https://github.com/SimonBoothroyd/splore

extra:
  recipe-maintainers:
    - simonboothroyd
